### ISSUE TITLE
Relax "nesbot/carbon" version requirement

### ISSUE THREAD

**Issue by wireblue** [kylekatarnls/business-day#4]
Hi there,

I wasn't able to install this library into my Laravel project (latest stable version, v5.6.23) as "business-day" requires "nesbot/carbon" 1.26+. Laravel requires 1.25.* and unfortunately I can't upgrade it.

Would it be possible to lower the "nesbot/carbon" version requirement for "business-day" to 1.25+?

Thanks

**Comment by kylekatarnls** [comment]
You should do this request to Laravel since we asked many times to unlock the carbon version for Laravel 5.6 (which is not needed in reality) but they refuse for stability reasons until now. Note: Laravel 5.7 support Carbon 1.26+.

business-day needs Carbon 1.26+ since it comes with its own macro system. We could support Carbon 1.25 in theory relying on laravel/support macro system. But as far as I know there is now way to say:
`"nesbot/carbon": "if illuminte/support then ^1.26 else ^1.25"`

I encourage you to ask the Laravel team to replace `1.25.*` with `1.25.* || ^1.26.3` to enable the support and bring new Carbon features to Laravel 5.6 explaining the limitation you get because this is the right way to fix it. It can make Laravel aware of such needs.

**Comment by kylekatarnls** [comment]
Note, you can try at your own risks to require `"nesbot/carbon": "1.28.0 as 1.25.0"`, or even use the dev branch: `"nesbot/carbon": "dev-master as 1.25.0"`

**Comment by wireblue** [comment]
Thanks @kylekatarnls.

It looks like a newer version of Carbon is coming in Laravel 5.7. It's a shame they won't likely backport it to Laravel 5.6 as 5.7 is probably still a few months away from being released.

I'm using your "1.28.0 as 1.25.0" suggestion for now and it seems to be working well. Thanks for that.

Hopefully this will pull us through until Laravel 5.7. :)
